### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by arckosfr** [danielquinn/paperless#136]
hello,

I don't know if i'm missing something but at the log output i think there is a missing dependance

``` bash
consumer_1   | Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
consumer_1   | Get:2 http://security.debian.org jessie/updates/main amd64 Packages [373 kB]
consumer_1   | Ign http://httpredir.debian.org jessie InRelease
consumer_1   | Get:3 http://httpredir.debian.org jessie Release.gpg [2373 B]
consumer_1   | Get:4 http://httpredir.debian.org jessie Release [148 kB]
consumer_1   | Get:5 http://httpredir.debian.org jessie-updates InRelease [142 kB]
consumer_1   | Get:6 http://httpredir.debian.org jessie/main amd64 Packages [9032 kB]
consumer_1   | Get:7 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.6 kB]
consumer_1   | Fetched 9778 kB in 6s (1442 kB/s)
consumer_1   | Reading package lists...
consumer_1   | dpkg-query: package 'tesseract-ocr-fra' is not installed and no information is available
consumer_1   | Use dpkg --info (= dpkg-deb --info) to examine archive files,
consumer_1   | and dpkg --contents (= dpkg-deb --contents) to list their contents.
consumer_1   | E: No packages found
consumer_1   | Starting document consumer at /consume
consumer_1   | Traceback (most recent call last):
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1   |     return self.cursor.execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
consumer_1   |     return Database.Cursor.execute(self, query, params)
consumer_1   | sqlite3.OperationalError: no such table: documents_log
consumer_1   |
consumer_1   | The above exception was the direct cause of the following exception:
consumer_1   |
consumer_1   | Traceback (most recent call last):
consumer_1   |   File "/usr/src/paperless/src/manage.py", line 18, in <module>
consumer_1   |     execute_from_command_line(sys.argv)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
consumer_1   |     utility.execute()
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
consumer_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
consumer_1   |     self.execute(*args, **cmd_options)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
consumer_1   |     output = self.handle(*args, **options)
consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 50, in handle
consumer_1   |     "Starting document consumer at {}".format(settings.CONSUMPTION_DIR)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1279, in info
consumer_1   |     self._log(INFO, msg, args, **kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1415, in _log
consumer_1   |     self.handle(record)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1425, in handle
consumer_1   |     self.callHandlers(record)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
consumer_1   |     hdlr.handle(record)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 855, in handle
consumer_1   |     self.emit(record)
consumer_1   |   File "/usr/src/paperless/src/documents/loggers.py", line 23, in emit
consumer_1   |     Log.objects.create(**kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
consumer_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 401, in create
consumer_1   |     obj.save(force_insert=True, using=self.db)
consumer_1   |   File "/usr/src/paperless/src/documents/models.py", line 260, in save
consumer_1   |     models.Model.save(self, *args, **kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 708, in save
consumer_1   |     force_update=force_update, update_fields=update_fields)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 736, in save_base
consumer_1   |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 820, in _save_table
consumer_1   |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 859, in _do_insert
consumer_1   |     using=using, raw=raw)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
consumer_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1039, in _insert
consumer_1   |     return query.get_compiler(using=using).execute_sql(return_id)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
consumer_1   |     cursor.execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
consumer_1   |     return super(CursorDebugWrapper, self).execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1   |     return self.cursor.execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
consumer_1   |     six.reraise(dj_exc_type, dj_exc_value, traceback)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
consumer_1   |     raise value.with_traceback(tb)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1   |     return self.cursor.execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
consumer_1   |     return Database.Cursor.execute(self, query, params)
consumer_1   | django.db.utils.OperationalError: no such table: documents_log
consumer_1   | Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
consumer_1   | Get:2 http://httpredir.debian.org jessie-updates InRelease [142 kB]
consumer_1   | Get:3 http://security.debian.org jessie/updates/main amd64 Packages [373 kB]
consumer_1   | Ign http://httpredir.debian.org jessie InRelease
consumer_1   | Get:4 http://httpredir.debian.org jessie-updates/main amd64 Packages [17.6 kB]
consumer_1   | Get:5 http://httpredir.debian.org jessie Release.gpg [2373 B]
consumer_1   | Get:6 http://httpredir.debian.org jessie Release [148 kB]
consumer_1   | Get:7 http://httpredir.debian.org jessie/main amd64 Packages [9032 kB]
consumer_1   | Fetched 9778 kB in 2s (3820 kB/s)
consumer_1   | Reading package lists...
consumer_1   | dpkg-query: package 'tesseract-ocr-fre' is not installed and no information is available
consumer_1   | Use dpkg --info (= dpkg-deb --info) to examine archive files,
consumer_1   | and dpkg --contents (= dpkg-deb --contents) to list their contents.
consumer_1   | E: No packages found
consumer_1   | Starting document consumer at /consume
consumer_1   | Traceback (most recent call last):
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1   |     return self.cursor.execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
consumer_1   |     return Database.Cursor.execute(self, query, params)
consumer_1   | sqlite3.OperationalError: no such table: documents_log
consumer_1   |
consumer_1   | The above exception was the direct cause of the following exception:
consumer_1   |
consumer_1   | Traceback (most recent call last):
consumer_1   |   File "/usr/src/paperless/src/manage.py", line 18, in <module>
consumer_1   |     execute_from_command_line(sys.argv)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 353, in execute_from_command_line
consumer_1   |     utility.execute()
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/__init__.py", line 345, in execute
consumer_1   |     self.fetch_command(subcommand).run_from_argv(self.argv)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 348, in run_from_argv
consumer_1   |     self.execute(*args, **cmd_options)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/core/management/base.py", line 399, in execute
consumer_1   |     output = self.handle(*args, **options)
consumer_1   |   File "/usr/src/paperless/src/documents/management/commands/document_consumer.py", line 50, in handle
consumer_1   |     "Starting document consumer at {}".format(settings.CONSUMPTION_DIR)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1279, in info
consumer_1   |     self._log(INFO, msg, args, **kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1415, in _log
consumer_1   |     self.handle(record)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1425, in handle
consumer_1   |     self.callHandlers(record)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 1487, in callHandlers
consumer_1   |     hdlr.handle(record)
consumer_1   |   File "/usr/local/lib/python3.5/logging/__init__.py", line 855, in handle
consumer_1   |     self.emit(record)
consumer_1   |   File "/usr/src/paperless/src/documents/loggers.py", line 23, in emit
consumer_1   |     Log.objects.create(**kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
consumer_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 401, in create
consumer_1   |     obj.save(force_insert=True, using=self.db)
consumer_1   |   File "/usr/src/paperless/src/documents/models.py", line 260, in save
consumer_1   |     models.Model.save(self, *args, **kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 708, in save
consumer_1   |     force_update=force_update, update_fields=update_fields)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 736, in save_base
consumer_1   |     updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 820, in _save_table
consumer_1   |     result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/base.py", line 859, in _do_insert
consumer_1   |     using=using, raw=raw)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/manager.py", line 122, in manager_method
consumer_1   |     return getattr(self.get_queryset(), name)(*args, **kwargs)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/query.py", line 1039, in _insert
consumer_1   |     return query.get_compiler(using=using).execute_sql(return_id)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/models/sql/compiler.py", line 1060, in execute_sql
consumer_1   |     cursor.execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 79, in execute
consumer_1   |     return super(CursorDebugWrapper, self).execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1   |     return self.cursor.execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/utils.py", line 95, in __exit__
consumer_1   |     six.reraise(dj_exc_type, dj_exc_value, traceback)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
consumer_1   |     raise value.with_traceback(tb)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/utils.py", line 64, in execute
consumer_1   |     return self.cursor.execute(sql, params)
consumer_1   |   File "/usr/local/lib/python3.5/site-packages/django/db/backends/sqlite3/base.py", line 323, in execute
consumer_1   |     return Database.Cursor.execute(self, query, params)
consumer_1   | django.db.utils.OperationalError: no such table: documents_log
```

I will try to take a look this week end tofix the dockerfile

**Comment by danielquinn** [comment]
From that output, it looks like `migrate` wasn't run, but [that step is indeed in the Dockerfile](https://github.com/danielquinn/paperless/blob/master/Dockerfile#L31)  Are you using docker-compose or trying to run things without it?

**Comment by arckosfr** [comment]
i use the compose file (more easier), and i don't know why he can find the french package for tesseract (he exist in debian stable)

**Comment by danielquinn** [comment]
Can you get it up and running with only english?  If you can, then we can look into why Debian is breaking here.

**Comment by arckosfr** [comment]
The output is the same (without the package missing) with english only

**Comment by danielquinn** [comment]
So you still see this?

```
consumer_1   |Fetched 9778 kB in 6s (1442 kB/s)
consumer_1   | Reading package lists...
consumer_1   | dpkg-query: package 'tesseract-ocr-fra' is not installed and no information is available
consumer_1   | Use dpkg --info (= dpkg-deb --info) to examine archive files,
consumer_1   | and dpkg --contents (= dpkg-deb --contents) to list their contents.
consumer_1   | E: No packages found
```

**Comment by danielquinn** [comment]
Can you post your `docker_compose.yml` file and `docker_compose.env` file?

**Comment by pitkley** [comment]
I have tested both using the Docker Hub image [`pitkley/paperless`](https://hub.docker.com/r/pitkley/paperless) (as is default in `docker-compose.yml.example`) and by building it directly from this repository. In both cases I copied the `.example` files and added `fra` as one of the OCR languages. Running `docker-compose up` successfully installs the `tesseract-ocr-fra` package and starts the consumer as expected.

Have you tried running Paperless **without** the `/data`, `/media` and `/consume` folders mounted?

-----

And as @danielquinn mentioned, posting your `yml` and `env` files might help tracking the issue down!

**Comment by arckosfr** [comment]
Yes, maybe something wrong with my compose : 

Docker-compose.yml : 
```
version: '2'

services:
    webserver:
        image: pitkley/paperless
        ports:
            # You can adapt the port you want Paperless to listen on by
            # modifying the part before the `:`.
            - "8000:8000"
        volumes:
            - /media/eb5180de-8f73-467f-b886-5c612bd07032/docker/paperless/data:/usr/src/paperless/data
            - /media/eb5180de-8f73-467f-b886-5c612bd07032/docker/paperless/media:/usr/src/paperless/media
        env_file: docker-compose.env
        # The reason the line is here is so that the webserver that doesn't do
        # any text recognition and doesn't have to install unnecessary
        # languages the user might have set in the env-file by overwriting the
        # value with nothing.
        environment:
            - PAPERLESS_OCR_LANGUAGES=
        command: ["runserver", "0.0.0.0:8000"]

    consumer:
        image: pitkley/paperless
        volumes:
            - /media/eb5180de-8f73-467f-b886-5c612bd07032/docker/paperless/data:/usr/src/paperless/data
            - /media/eb5180de-8f73-467f-b886-5c612bd07032/docker/paperless/media:/usr/src/paperless/media
            # You have to adapt the local path you want the consumption
            # directory to mount to by modifying the part before the ':'.
            - /media/eb5180de-8f73-467f-b886-5c612bd07032/docker/paperless/depose:/consume
            # Likewise, you can add a local path to mount a directory for
            # exporting. This is not strictly needed for paperless to
            # function, only if you're exporting your files: uncomment
            # it and fill in a local path if you know you're going to
            # want to export your documents.
            # - /path/to/another/arbitrary/place:/export
        env_file: docker-compose.env
        command: ["document_consumer"]

volumes:
    data:
    media:
```

docker-compose.env
```
# Environment variables to set for Paperless
# Commented out variables will be replaced by a default within Paperless.

# Passphrase Paperless uses to encrypt and decrypt your documents
PAPERLESS_PASSPHRASE=somepassphrase

# The amount of threads to use for text recognition
PAPERLESS_OCR_THREADS=2

# Additional languages to install for text recognition
# PAPERLESS_OCR_LANGUAGES=fra

# You can change the default user and group id to a custom one
# USERMAP_UID=1000
# USERMAP_GID=1000
```

I don't know very well the compose v2 maybe i missed something

**Comment by gunr2171** [comment]
I've got the same problem it seems, most likely has to do with how we are voluming our folders.

```
paperless_web:
  image: pitkley/paperless
  container_name: paperless_web
  volumes:
    - /services/docker-compose/paperless/data:/usr/src/paperless/data
    - /services/docker-compose/paperless/media:/usr/src/paperless/media
  environment:
    - PAPERLESS_PASSPHRASE=somepassphrase
    - PAPERLESS_OCR_LANGUAGES=
  expose:
    - 80
  command: ["runserver", "0.0.0.0:80"]
  #restart: unless-stopped

paperless_consumer:
  image: pitkley/paperless
  container_name: paperless_consumer
  volumes:
    - /services/docker-compose/paperless/data:/usr/src/paperless/data
    - /services/docker-compose/paperless/media:/usr/src/paperless/media
    - /services/docker-compose/paperless/consume:/consume
    - /services/docker-compose/paperless/export:/export
  environment:
    - PAPERLESS_PASSPHRASE=somepassphrase
    - PAPERLESS_OCR_LANGUAGES=

  command: ["document_consumer"]
  #restart: unless-stopped
```

Some things to note about my `docker-compose` file:
* I'm using Compose version 1. Due to how my production system is laid out, I can't use version 2. Of course, that means I can't use named volumes. That's why I have everything mapped to the host system.
* I'm choosing not to use the ENV file. Personally, I'd prefer to have all the environment variables in the docker-compose file so they are all in the same location.
* I'm exposing port 80 rather than publishing the port because another docker container, haproxy, will link to it and give it traffic.

For comparison, this is the `docker-compose` file I used for testing (not production) which _does_ use Version 2, and is more or less a straight copy of the example in this repository.

`docker-compose.yml`
```
version: '2'

services:
    webserver:
        image: pitkley/paperless
        ports:
            - "8000:8000"
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
        env_file: docker-compose.env
        environment:
            - PAPERLESS_OCR_LANGUAGES=
        command: ["runserver", "0.0.0.0:8000"]

    consumer:
        image: pitkley/paperless
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media

            - /home/kevin/docker/paperless/consume:/consume
            - /home/kevin/docker/paperless/export:/export
        env_file: docker-compose.env
        command: ["document_consumer"]

volumes:
    data:
    media:
```

`docker-compose.env`
```
# Passphrase Paperless uses to encrypt and decrypt your documents
PAPERLESS_PASSPHRASE=somepassphrase

#<all others are commented out>
```

Once I ran `chmod 777 /home/kevin/docker/paperless/consume` all seemed to work with my testing instance.

---

With the production instance, I `chmod 777`'d all the directories that were volumed, however those errors originally reported did not stop.

Also, I'm not getting the debian "can't find package" errors in my logs, I'm getting

    ...
    django.db.utils.OperationalError: no such table: documents_log
