### ISSUE TITLE
Docker : no CSS files

### ISSUE THREAD

**Issue by J-Ha** [danielquinn/paperless#198]
I ran into this error, while setting up paperless-docker.

![screenshot 2017-03-12 um 00 06 48](https://cloud.githubusercontent.com/assets/7397248/23827648/33afd6f8-06b8-11e7-91d6-3689d5e3ec69.jpg)
Failed to load resource: the server responded with a status of 404 (Not Found)

**Comment by kakawait** [comment]
@J-Ha how did you fix it?

**Comment by MasterofJOKers** [comment]
@kakawait My guess would be, that there was a "python manage.py collectstatic" missing somewhere. IIRC, I also ran into similar issues (without docker), as the setup documentation doesn't tell you about it.

**Comment by danielquinn** [comment]
@MasterofJOKers if you find the documentation lacking, please feel free to issue a PR with a fix.

**Comment by kakawait** [comment]
@MasterofJOKers I ran `python3 manage.py collectstatic` but does not change... even if command successfully ran

```
root@cf74ae60b1f4:/usr/src/paperless/src# python3 manage.py collectstatic

You have requested to collect static files at the destination
location as specified in your settings:

    /usr/src/paperless/static

This will overwrite existing files!
Are you sure you want to do this?

Type 'yes' to continue, or 'no' to cancel: yes
Copying '/usr/local/lib/python3.5/site-packages/django_extensions/static/django_extensions/css/jquery.autocomplete.css'
Copying '/usr/local/lib/python3.5/site-packages/django_extensions/static/django_extensions/js/jquery.autocomplete.js'
...
Copying '/usr/local/lib/python3.5/site-packages/rest_framework/static/rest_framework/docs/img/favicon.ico'
Copying '/usr/local/lib/python3.5/site-packages/rest_framework/static/rest_framework/docs/img/grid.png'
Copying '/usr/local/lib/python3.5/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings.png'
Copying '/usr/local/lib/python3.5/site-packages/rest_framework/static/rest_framework/img/glyphicons-halflings-white.png'
Copying '/usr/local/lib/python3.5/site-packages/rest_framework/static/rest_framework/img/grid.png'

115 static files copied to '/usr/src/paperless/static'.
```

Here my docker files (compose and env)

```yml
version: '2'
services:
    webserver:
        image: pitkley/paperless
        ports:
            - "8000:8000"
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
        env_file: docker-compose.env
        environment:
            - PAPERLESS_OCR_LANGUAGES=
        command: ["runserver", "0.0.0.0:8000"]

    consumer:
        image: pitkley/paperless
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            - ./data:/consume
        env_file: docker-compose.env
        command: ["document_consumer"]

volumes:
    data:
    media:
```

```
# Environment variables to set for Paperless
# Commented out variables will be replaced by a default within Paperless.

# Passphrase Paperless uses to encrypt and decrypt your documents
PAPERLESS_PASSPHRASE=CHANGE_ME

# The amount of threads to use for text recognition
# PAPERLESS_OCR_THREADS=4

# Additional languages to install for text recognition
PAPERLESS_OCR_LANGUAGES=fra

# You can change the default user and group id to a custom one
# USERMAP_UID=1000
# USERMAP_GID=1000
```
