### ISSUE TITLE
Problem with mail consuming

### ISSUE THREAD

**Issue by ClocxHD** [danielquinn/paperless#296]
Hello,

i have the following issue with the mail consuming:
If the consumer tries to get the mails, i get the following error:
consumer_1   | Starting document consumer at /consume
consumer_1   | Starting document consumer at /consume
consumer_1   | 'in <string>' requires string as left operand, not NoneType

The mail is marked as read, but the attached PDF-File is not consumed.

Any ideas?

**Comment by danielquinn** [comment]
Yeah that's no good.  Not a lot to go on either.  Is there a way you can get me a traceback to work with?  'Cause at this point all I can think of is doing `grep in` which is not going to end well.

Does this happen if you try to consume documents simply by putting them in the consume folder, or is it *only* by mail?

**Comment by ClocxHD** [comment]
It only happens by mail, putting them in the consume folder works just fine.

If you tell me how i get a traceback i provide this to you

**Comment by danielquinn** [comment]
Basically what I need is the complete output of the `consumer_1` container, so if you're using docker-compose (as that's what it looks  like), there *should* be more output around the error message, preferably something with a line number so I know which `in` it's talking about.

I believe the easiest way to get this is to use `docker logs consumer_1` and just copy/paste the relevant bit of output, probably about 30 lines or so around the document in question.  Additionally, if you're willing to share the document, that might go a long way toward me reproducing the problem locally.

**Comment by asfalots** [comment]
Hi, 
I have the same issue but infortunatly the logs are not very verbose:
```
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, documents, reminders, sessions
Running migrations:
  No migrations to apply.
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.7/community/x86_64/APKINDEX.tar.gz
(1/1) Installing tesseract-ocr-data-fra (3.05.01-r2)
OK: 320 MiB in 119 packages
Starting document consumer at /consume
'in <string>' requires string as left operand, not NoneType
```
I'm using the dockerhub image on latest tag. Here is the docker-compose section for consumer:
```
consumer:
    image: danielquinn/paperless:latest
    environment:
      - PAPERLESS_PASSPHRASE=you will not know
      - PAPERLESS_OCR_LANGUAGES=fra eng
      - PAPERLESS_CONSUME_MAIL_HOST=imap.gmail.com
      - PAPERLESS_CONSUME_MAIL_PORT=993
      - PAPERLESS_CONSUME_MAIL_USER=toto@gmail.com
      - PAPERLESS_CONSUME_MAIL_PASS=mysuperpassword
      - PAPERLESS_CONSUME_MAIL_INBOX=INBOX
    depends_on:
      - server
    volumes:
      - type: bind
        source: /data/paperless/data
        target: /usr/src/paperless/data
      - type: bind
        source: /data/paperless/media
        target: /usr/src/paperless/media
      - type: bind
        source: /data/paperless/consume
        target: /consume
    command: ["document_consumer"]
    networks:
      - netProxy
```

same behavior, mail mark as read but document not processed.  I have tried with different documents and always have the same error.

NB: I love paperless, bless you for the work you made
