### ISSUE TITLE
consuming file fails due to several reasons

### ISSUE THREAD

**Issue by daedadu** [danielquinn/paperless#406]
I'm german and trying to scan a document. So you bet there are some nasty characters in this file like "ä,ü" and so on ;). I'm running this in docker, this is my first docker experience.

When running `./manage.py document_consumer` i get the following:

```
bash-4.4# ./manage.py document_consumer
Starting document consumer at /consume with inotify
Parsers available: RasterisedDocumentParser
Consuming /consume/Scannen.pdf
Processing sheet #1: /tmp/paperless/paperless-pjkrcr4l/convert-0000.pnm -> /tmp/paperless/paperless-pjkrcr4l/convert-0000.unpaper.pnm
[pgm_pipe @ 0x5650674ba700] Stream #0: not enough frames to estimate rate; consider increasing probesize
out of deviation range - NO ROTATING
[image2 @ 0x5650674bb720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x5650674bb720] Encoder did not produce proper pts, making some up.
OCRing the document
Parsing for eng
Parsing for deu
Processing sheet #1: /tmp/paperless/paperless-pjkrcr4l/convert-0000.unpaper.pnm -> /tmp/paperless/paperless-pjkrcr4l/convert-0000.unpaper.unpaper.pnm
unpaper: error: output file '/tmp/paperless/paperless-pjkrcr4l/convert-0000.unpaper.pnm' already present.

Try 'man unpaper' for more information.
[pgm_pipe @ 0x5628ef2f3700] Stream #0: not enough frames to estimate rate; consider increasing probesize
out of deviation range - NO ROTATING
[image2 @ 0x5628ef2f4720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x5628ef2f4720] Encoder did not produce proper pts, making some up.
PARSE FAILURE for /consume/Scannen.pdf: Unpaper failed at ('unpaper', '/tmp/paperless/paperless-pjkrcr4l/convert-0000.pnm', '/tmp/paperless/paperless-pjkrcr4l/convert-0000.unpaper.pnm')
```

Replacing `command_args = unpaper, pnm, pnm.replace(".pnm",".unpaper.pnm")` in `parsers.py`

by

`command_args = unpaper,"--overwrite", pnm, pnm.replace(".pnm",".unpaper.pnm")`

gets me another step further.

```
bash-4.4# ./manage.py document_consumer
Starting document consumer at /consume with inotify
Parsers available: RasterisedDocumentParser
Consuming /consume/Scannen.pdf
Processing sheet #1: /tmp/paperless/paperless-jzksumkz/convert-0000.pnm -> /tmp/paperless/paperless-jzksumkz/convert-0000.unpaper.pnm
[pgm_pipe @ 0x55cd44f12700] Stream #0: not enough frames to estimate rate; consider increasing probesize
out of deviation range - NO ROTATING
[image2 @ 0x55cd44f13720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x55cd44f13720] Encoder did not produce proper pts, making some up.
OCRing the document
Parsing for eng
Parsing for deu
Processing sheet #1: /tmp/paperless/paperless-jzksumkz/convert-0000.unpaper.pnm -> /tmp/paperless/paperless-jzksumkz/convert-0000.unpaper.unpaper.pnm
Processing sheet #1: /tmp/paperless/paperless-jzksumkz/convert-0000.pnm -> /tmp/paperless/paperless-jzksumkz/convert-0000.unpaper.pnm
[pgm_pipe @ 0x55c807f10700] Stream #0: not enough frames to estimate rate; consider increasing probesize
[pgm_pipe @ 0x562001eb8700] Stream #0: not enough frames to estimate rate; consider increasing probesize
out of deviation range - NO ROTATING
out of deviation range - NO ROTATING
[image2 @ 0x55c807f11720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x55c807f11720] Encoder did not produce proper pts, making some up.
[image2 @ 0x562001eb9720] Using AVStream.codec to pass codec parameters to muxers is deprecated, use AVStream.codecpar instead.
[image2 @ 0x562001eb9720] Encoder did not produce proper pts, making some up.
OCRing the document
Parsing for eng
Parsing for deu
PARSE FAILURE for /consume/Scannen.pdf: The guessed language is not available in this instance of Tesseract.
```

I debugged into this as well and it seems the second call delivers some letters that don't make any sense which leads the language detection to a failure. When replacing `settings.FORGIVING_OCR` with `True` the process runs through. But the recognized documents have wrong letters at the position where the german umlauts are.

To me it appears there might be several problems here. 

- First it looks like the test for several languages leads to double namings somehow. Thats why `--overwrite` seems to help.
- how can I change `settings.FORGIVING_OCR` from a config file? Shouldn't this go through anyway?

I would appreciate some help here, I'm willing to fix this myself and to make a pull request. But as for now I don't understand enough of this project to do this. Maybe someone can hint me in the right direction or make the fix him/herself ;)

**Comment by daedadu** [comment]
That fiexed it for me as well, looks like PAPERLESS_OCR_LANGUAGES isn't working

**Comment by thepill** [comment]
Im facing a similar problem because it tries to detect the page in languages i dont have/want.

For e.g. some german texts are scanned as `deu` and  ìnd`.
the output text wich is stored in paperless is than not german...

**Comment by euri10** [comment]
I think the issue is that the build doesn't install the lang according to the env passed, 
I fixed it with this Dockerfile diff and the below docker-compose 

```
version: '3.6'
services:
  webserver:
    build: ./
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD", "curl" , "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
        - data:/usr/src/paperless/data
        - media:/usr/src/paperless/media
    env_file: docker-compose.env
    environment:
      - PAPERLESS_OCR_LANGUAGES=fra
    command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]

  consumer:
    build:
      context: .
      args:
        - PAPERLESS_OCR_LANGUAGES=fra
    depends_on:
      - webserver
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
    env_file: docker-compose.env
    command: ["document_consumer"]

volumes:
    data:
    media:
```


```
--- Dockerfile	(revision a511d34d694faf907aabdff67b019ae37231d47b)
+++ Dockerfile	(date 1537781615000)
@@ -35,6 +35,9 @@
 # Setup entrypoint
     chmod 755 /sbin/docker-entrypoint.sh
 
+ARG PAPERLESS_OCR_LANGUAGES
+RUN for i in ${PAPERLESS_OCR_LANGUAGES} ; do apk add tesseract-ocr-data-"$i"; done
+
 WORKDIR /usr/src/paperless/src
 # Mount volumes and set Entrypoint
 VOLUME ["/usr/src/paperless/data", "/usr/src/paperless/media", "/consume", "/export"]
```
