### ISSUE TITLE
Docker + NFS issue

### ISSUE THREAD

**Issue by cribbstechnologies** [danielquinn/paperless#482]
I've got two NFS mounts for the paperless directories

```
/paperless/scans
/paperless/processed
```

permissions on parent 
```
drwxr-sr-x   6 paperless paperless  4096 Jan 20 17:32 paperless/
```

Permissions on children:
```
drwxrwsrwx   4 paperless paperless 4096 Jan 21 04:04 processed/
drwxrwsrwx   4 paperless paperless 4096 Jan 21 04:27 scans/
```

They're coming from a synology NAS so I can't control gid or uid on that end so I had to assign them in the docker compose
```
USERMAP_UID=1043
USERMAP_GID=65537
```

and output of `sudo id paperless`
```
uid=1043(paperless) gid=65537(paperless) groups=65537(paperless)
```

if I write a file into `/paperless/scans` while the container is running, nothing happens. I can copy multiple files in there and nothing happens and the logs don't change. If I restart the docker container the files are processed just fine

What am I doing wrong?

docker-compose.yml
```
version: '2.1'

services:
    webserver:
        build: ./
        # uncomment the following line to start automatically on system boot
        # restart: always
        ports:
            # You can adapt the port you want Paperless to listen on by
            # modifying the part before the `:`.
            - "8000:8000"
        healthcheck:
            test: ["CMD", "curl" , "-f", "http://localhost:8000"]
            interval: 30s
            timeout: 10s
            retries: 5
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            # You have to adapt the local path you want the consumption
            # directory to mount to by modifying the part before the ':'.
            - /paperless/scans:/consume
        env_file: docker-compose.env
        # The reason the line is here is so that the webserver that doesn't do
        # any text recognition and doesn't have to install unnecessary
        # languages the user might have set in the env-file by overwriting the
        # value with nothing.
        environment:
            - PAPERLESS_OCR_LANGUAGES=
        command: ["runserver", "--insecure", "--noreload", "0.0.0.0:8000"]

    consumer:
        build: ./
        # uncomment the following line to start automatically on system boot
        # restart: always
        depends_on:
            webserver:
                condition: service_healthy
        volumes:
            - data:/usr/src/paperless/data
            - media:/usr/src/paperless/media
            # This should be set to the same value as the consume director
            # in the webserver service above.
            - /paperless/scans:/consume
            # Likewise, you can add a local path to mount a directory for
            # exporting. This is not strictly needed for paperless to
            # function, only if you're exporting your files: uncomment
            # it and fill in a local path if you know you're going to
            # want to export your documents.
            - /paperless/processed:/export
        env_file: docker-compose.env
        command: ["document_consumer"]

volumes:
    data:
    media:
```
